//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ookii.CommandLine.Generator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ookii.CommandLine.Generator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The arguments class {0} may not be a generic class when the GeneratedParserAttribute is used..
        /// </summary>
        internal static string ArgumentsClassIsGenericMessageFormat {
            get {
                return ResourceManager.GetString("ArgumentsClassIsGenericMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The arguments class may not be a generic type..
        /// </summary>
        internal static string ArgumentsClassIsGenericTitle {
            get {
                return ResourceManager.GetString("ArgumentsClassIsGenericTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The arguments class {0} must use the &apos;partial&apos; modifier..
        /// </summary>
        internal static string ArgumentsClassNotPartialMessageFormat {
            get {
                return ResourceManager.GetString("ArgumentsClassNotPartialMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The arguments class must be a partial class..
        /// </summary>
        internal static string ArgumentsClassNotPartialTitle {
            get {
                return ResourceManager.GetString("ArgumentsClassNotPartialTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The arguments type {0} must be a reference type (class)..
        /// </summary>
        internal static string ArgumentsTypeNotReferenceTypeMessageFormat {
            get {
                return ResourceManager.GetString("ArgumentsTypeNotReferenceTypeMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The arguments type must be a reference type..
        /// </summary>
        internal static string ArgumentsTypeNotReferenceTypeTitle {
            get {
                return ResourceManager.GetString("ArgumentsTypeNotReferenceTypeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The multi-value argument defined by {0}.{1} must have an array rank of one..
        /// </summary>
        internal static string InvalidArrayRankMessageFormat {
            get {
                return ResourceManager.GetString("InvalidArrayRankMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A multi-value argument defined by an array properties must have an array rank of one..
        /// </summary>
        internal static string InvalidArrayRankTitle {
            get {
                return ResourceManager.GetString("InvalidArrayRankTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property {0}.{1} must have a public set accessor..
        /// </summary>
        internal static string PropertyIsReadOnlyMessageFormat {
            get {
                return ResourceManager.GetString("PropertyIsReadOnlyMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An argument property must have a public set accessor..
        /// </summary>
        internal static string PropertyIsReadOnlyTitle {
            get {
                return ResourceManager.GetString("PropertyIsReadOnlyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The attribute {0} is unknown and will be ignored by the GeneratedParserAttribute..
        /// </summary>
        internal static string UnknownAttributeMessageFormat {
            get {
                return ResourceManager.GetString("UnknownAttributeMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown attribute will be ignored..
        /// </summary>
        internal static string UnknownAttributeTitle {
            get {
                return ResourceManager.GetString("UnknownAttributeTitle", resourceCulture);
            }
        }
    }
}
