version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/src"
    schedule:
      interval: "daily"
    target-branch: "main"
    groups:
       # Group all dependencies in one PR.
       nuget-dependencies:
          patterns:
             - "*"
    ignore:
        # 4.3.x is the latest version that can work with the .Net 6.0 SDK for both of these.
      - dependency-name: "Microsoft.CodeAnalysis.CSharp"
        update-types: ["version-update:semver-major", "version-update:semver-minor"]
      - dependency-name: "Microsoft.CodeAnalysis.CSharp.Workspaces"
        update-types: ["version-update:semver-major", "version-update:semver-minor"]
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "main"
