//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.237
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ookii.CommandLine.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ookii.CommandLine.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value &apos;{0}&apos; provided for argument &apos;{1}&apos; could not be interpreted as a &apos;{2}&apos;..
        /// </summary>
        internal static string ArgumentConversionErrorFormat {
            get {
                return ResourceManager.GetString("ArgumentConversionErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name for argument &apos;{0}&apos; contains a colon (:), which is not allowed..
        /// </summary>
        internal static string ArgumentNameContainsSeparatorFormat {
            get {
                return ResourceManager.GetString("ArgumentNameContainsSeparatorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A positional array argument must be the last positional argument..
        /// </summary>
        internal static string ArrayNotLastArgument {
            get {
                return ResourceManager.GetString("ArrayNotLastArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0,13} : {1}
        ///.
        /// </summary>
        internal static string DefaultArgumentDescriptionFormat {
            get {
                return ResourceManager.GetString("DefaultArgumentDescriptionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ....
        /// </summary>
        internal static string DefaultArraySuffix {
            get {
                return ResourceManager.GetString("DefaultArraySuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following commands are available:.
        /// </summary>
        internal static string DefaultAvailableCommandsHeader {
            get {
                return ResourceManager.GetString("DefaultAvailableCommandsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0,13} : {1}
        ///.
        /// </summary>
        internal static string DefaultCommandFormat {
            get {
                return ResourceManager.GetString("DefaultCommandFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} &lt;command&gt; [args...].
        /// </summary>
        internal static string DefaultCommandUsageFormat {
            get {
                return ResourceManager.GetString("DefaultCommandUsageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}].
        /// </summary>
        internal static string DefaultOptionalArgumentFormat {
            get {
                return ResourceManager.GetString("DefaultOptionalArgumentFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage: {0}.
        /// </summary>
        internal static string DefaultUsagePrefixFormat {
            get {
                return ResourceManager.GetString("DefaultUsagePrefixFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;{0}&gt;.
        /// </summary>
        internal static string DefaultValueDescriptionFormat {
            get {
                return ResourceManager.GetString("DefaultValueDescriptionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The argument &apos;{0}&apos; was supplied more than once..
        /// </summary>
        internal static string DuplicateArgumentFormat {
            get {
                return ResourceManager.GetString("DuplicateArgumentFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The argument &apos;{0}&apos; has the same position value as the argument &apos;{1}&apos;..
        /// </summary>
        internal static string DuplicateArgumentPositionFormat {
            get {
                return ResourceManager.GetString("DuplicateArgumentPositionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The argument name cannot be empty..
        /// </summary>
        internal static string EmptyArgumentName {
            get {
                return ResourceManager.GetString("EmptyArgumentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An argument name prefix may not be null or an empty string..
        /// </summary>
        internal static string EmptyArgumentNamePrefix {
            get {
                return ResourceManager.GetString("EmptyArgumentNamePrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must specify at least one argument name prefix..
        /// </summary>
        internal static string EmptyArgumentNamePrefixes {
            get {
                return ResourceManager.GetString("EmptyArgumentNamePrefixes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type of the default value for argument &apos;{0}&apos; is not compatible with the type of the argument..
        /// </summary>
        internal static string IncorrectDefaultValueTypeFormat {
            get {
                return ResourceManager.GetString("IncorrectDefaultValueTypeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The indent must be greater than or equal to zero, and less than the maximum line length..
        /// </summary>
        internal static string IndentOutOfRange {
            get {
                return ResourceManager.GetString("IndentOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offset and length were out of bounds for the array or count is greater than the number of elements from index to the end of the source collection..
        /// </summary>
        internal static string IndexCountOutOfRange {
            get {
                return ResourceManager.GetString("IndexCountOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multi-dimensional arrays are not supported for command line arguments..
        /// </summary>
        internal static string InvalidArrayRank {
            get {
                return ResourceManager.GetString("InvalidArrayRank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The command line constructor cannot have non-optional arguments after an optional argument..
        /// </summary>
        internal static string InvalidOptionalArgumentOrder {
            get {
                return ResourceManager.GetString("InvalidOptionalArgumentOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified property is not a command line argument..
        /// </summary>
        internal static string MissingArgumentAttribute {
            get {
                return ResourceManager.GetString("MissingArgumentAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The required argument &apos;{0}&apos; was not supplied..
        /// </summary>
        internal static string MissingRequiredArgumentFormat {
            get {
                return ResourceManager.GetString("MissingRequiredArgumentFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No value was supplied for the argument &apos;{0}&apos;..
        /// </summary>
        internal static string MissingValueForNamedArgumentFormat {
            get {
                return ResourceManager.GetString("MissingValueForNamedArgumentFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The command line arguments type has more than one constructor with the CommandLineConstructorAttribute attribute..
        /// </summary>
        internal static string MultipleMarkedConstructors {
            get {
                return ResourceManager.GetString("MultipleMarkedConstructors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The command line arguments type does not have any public constructors..
        /// </summary>
        internal static string NoConstructor {
            get {
                return ResourceManager.GetString("NoConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The command line arguments type has more than one constructor, none of which has the CommandLineConstructorAttribute attribute..
        /// </summary>
        internal static string NoMarkedConstructor {
            get {
                return ResourceManager.GetString("NoMarkedConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The argument &apos;{0}&apos; has type &apos;{1}&apos; that for which no type converter exists that can convert from a string..
        /// </summary>
        internal static string NoTypeConverterFormat {
            get {
                return ResourceManager.GetString("NoTypeConverterFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property defining the argument &apos;{0}&apos; doesn&apos;t have a public set accessor..
        /// </summary>
        internal static string PropertyIsReadOnlyFormat {
            get {
                return ResourceManager.GetString("PropertyIsReadOnlyFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many arguments were supplied..
        /// </summary>
        internal static string TooManyArguments {
            get {
                return ResourceManager.GetString("TooManyArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos; does not derive from the ShellCommand class or does not define the ShellCommandAttribute attribute..
        /// </summary>
        internal static string TypeIsNotShellCommandFormat {
            get {
                return ResourceManager.GetString("TypeIsNotShellCommandFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type must be the generic type definition of a generic interface..
        /// </summary>
        internal static string TypeNotGenericInterface {
            get {
                return ResourceManager.GetString("TypeNotGenericInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown argument name &apos;{0}&apos;..
        /// </summary>
        internal static string UnknownArgumentFormat {
            get {
                return ResourceManager.GetString("UnknownArgumentFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value must be zero or larger..
        /// </summary>
        internal static string ValueMustBeNonNegative {
            get {
                return ResourceManager.GetString("ValueMustBeNonNegative", resourceCulture);
            }
        }
    }
}
