//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ookii.CommandLine.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ookii.CommandLine.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value &apos;{0}&apos; provided for argument &apos;{1}&apos; could not be interpreted as a &apos;{2}&apos;..
        /// </summary>
        internal static string ArgumentConversionErrorFormat {
            get {
                return ResourceManager.GetString("ArgumentConversionErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name for argument &apos;{0}&apos; contains a colon (:), which is not allowed..
        /// </summary>
        internal static string ArgumentNameContainsSeparatorFormat {
            get {
                return ResourceManager.GetString("ArgumentNameContainsSeparatorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A positional array argument must be the last positional argument..
        /// </summary>
        internal static string ArrayNotLastArgument {
            get {
                return ResourceManager.GetString("ArrayNotLastArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays this help message..
        /// </summary>
        internal static string AutomaticHelpDescription {
            get {
                return ResourceManager.GetString("AutomaticHelpDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string AutomaticHelpName {
            get {
                return ResourceManager.GetString("AutomaticHelpName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to h.
        /// </summary>
        internal static string AutomaticHelpShortAlias {
            get {
                return ResourceManager.GetString("AutomaticHelpShortAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?.
        /// </summary>
        internal static string AutomaticHelpShortName {
            get {
                return ResourceManager.GetString("AutomaticHelpShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to version.
        /// </summary>
        internal static string AutomaticVersionCommandName {
            get {
                return ResourceManager.GetString("AutomaticVersionCommandName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays version information..
        /// </summary>
        internal static string AutomaticVersionDescription {
            get {
                return ResourceManager.GetString("AutomaticVersionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string AutomaticVersionName {
            get {
                return ResourceManager.GetString("AutomaticVersionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The arguments are not valid..
        /// </summary>
        internal static string ClassValidationFailed {
            get {
                return ResourceManager.GetString("ClassValidationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The combined short argument &apos;{0}&apos; contains an argument that is not a switch..
        /// </summary>
        internal static string CombinedShortNameNonSwitchFormat {
            get {
                return ResourceManager.GetString("CombinedShortNameNonSwitchFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred creating an instance of the arguments type: {0}.
        /// </summary>
        internal static string CreateArgumentsTypeErrorFormat {
            get {
                return ResourceManager.GetString("CreateArgumentsTypeErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [arguments].
        /// </summary>
        internal static string DefaultAbbreviatedRemainingArguments {
            get {
                return ResourceManager.GetString("DefaultAbbreviatedRemainingArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ....
        /// </summary>
        internal static string DefaultArraySuffix {
            get {
                return ResourceManager.GetString("DefaultArraySuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following commands are available:.
        /// </summary>
        internal static string DefaultAvailableCommandsHeader {
            get {
                return ResourceManager.GetString("DefaultAvailableCommandsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  &lt;command&gt; [arguments].
        /// </summary>
        internal static string DefaultCommandUsageSuffix {
            get {
                return ResourceManager.GetString("DefaultCommandUsageSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Default value: {0}..
        /// </summary>
        internal static string DefaultDefaultValueFormat {
            get {
                return ResourceManager.GetString("DefaultDefaultValueFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage:.
        /// </summary>
        internal static string DefaultUsagePrefix {
            get {
                return ResourceManager.GetString("DefaultUsagePrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The argument &apos;{0}&apos; was supplied more than once..
        /// </summary>
        internal static string DuplicateArgumentFormat {
            get {
                return ResourceManager.GetString("DuplicateArgumentFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The argument &apos;{0}&apos; has the same position value as the argument &apos;{1}&apos;..
        /// </summary>
        internal static string DuplicateArgumentPositionFormat {
            get {
                return ResourceManager.GetString("DuplicateArgumentPositionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The argument &apos;{0}&apos; cannot have an empty alias..
        /// </summary>
        internal static string EmptyAliasFormat {
            get {
                return ResourceManager.GetString("EmptyAliasFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The argument name cannot be empty..
        /// </summary>
        internal static string EmptyArgumentName {
            get {
                return ResourceManager.GetString("EmptyArgumentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An argument name prefix may not be null or an empty string..
        /// </summary>
        internal static string EmptyArgumentNamePrefix {
            get {
                return ResourceManager.GetString("EmptyArgumentNamePrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must specify at least one argument name prefix..
        /// </summary>
        internal static string EmptyArgumentNamePrefixes {
            get {
                return ResourceManager.GetString("EmptyArgumentNamePrefixes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The key-value separator cannot be an empty string..
        /// </summary>
        internal static string EmptyKeyValueSeparator {
            get {
                return ResourceManager.GetString("EmptyKeyValueSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The indent must be greater than or equal to zero, and less than the maximum line length..
        /// </summary>
        internal static string IndentOutOfRange {
            get {
                return ResourceManager.GetString("IndentOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offset and length were out of bounds for the array or count is greater than the number of elements from index to the end of the source collection..
        /// </summary>
        internal static string IndexCountOutOfRange {
            get {
                return ResourceManager.GetString("IndexCountOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multi-dimensional arrays are not supported for command line arguments..
        /// </summary>
        internal static string InvalidArrayRank {
            get {
                return ResourceManager.GetString("InvalidArrayRank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value &apos;{1}&apos; provided for argument &apos;{0}&apos; was invalid: {2}.
        /// </summary>
        internal static string InvalidDictionaryValueFormat {
            get {
                return ResourceManager.GetString("InvalidDictionaryValueFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The method &apos;{0}&apos; has an unsupported signature..
        /// </summary>
        internal static string InvalidMethodSignatureFormat {
            get {
                return ResourceManager.GetString("InvalidMethodSignatureFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The command line constructor cannot have non-optional arguments after an optional argument..
        /// </summary>
        internal static string InvalidOptionalArgumentOrder {
            get {
                return ResourceManager.GetString("InvalidOptionalArgumentOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid standard stream value..
        /// </summary>
        internal static string InvalidStandardStream {
            get {
                return ResourceManager.GetString("InvalidStandardStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;minimum&apos; and &apos;maximum&apos; parameters cannot both be null..
        /// </summary>
        internal static string MinMaxBothNull {
            get {
                return ResourceManager.GetString("MinMaxBothNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified property or method is not a command line argument..
        /// </summary>
        internal static string MissingArgumentAttribute {
            get {
                return ResourceManager.GetString("MissingArgumentAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The required argument &apos;{0}&apos; was not supplied..
        /// </summary>
        internal static string MissingRequiredArgumentFormat {
            get {
                return ResourceManager.GetString("MissingRequiredArgumentFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No value was supplied for the argument &apos;{0}&apos;..
        /// </summary>
        internal static string MissingValueForNamedArgumentFormat {
            get {
                return ResourceManager.GetString("MissingValueForNamedArgumentFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The command line arguments type has more than one constructor with the CommandLineConstructorAttribute attribute..
        /// </summary>
        internal static string MultipleMarkedConstructors {
            get {
                return ResourceManager.GetString("MultipleMarkedConstructors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The command line arguments type does not have any public constructors..
        /// </summary>
        internal static string NoConstructor {
            get {
                return ResourceManager.GetString("NoConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A key/value pair must contain &quot;{0}&quot; as a separator..
        /// </summary>
        internal static string NoKeyValuePairSeparatorFormat {
            get {
                return ResourceManager.GetString("NoKeyValuePairSeparatorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The argument &apos;{0}&apos; cannot be accessed by either long or short name..
        /// </summary>
        internal static string NoLongOrShortName {
            get {
                return ResourceManager.GetString("NoLongOrShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The command line arguments type has more than one constructor, none of which has the CommandLineConstructorAttribute attribute..
        /// </summary>
        internal static string NoMarkedConstructor {
            get {
                return ResourceManager.GetString("NoMarkedConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The argument &apos;{0}&apos; has type &apos;{1}&apos;, which does not have a TypeConverter that can convert from a string. Use the TypeConverterAttribute to specify a custom TypeConverter..
        /// </summary>
        internal static string NoTypeConverterForArgumentFormat {
            get {
                return ResourceManager.GetString("NoTypeConverterForArgumentFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No type converter that can convert to and from a string exists for type &apos;{0}&apos;..
        /// </summary>
        internal static string NoTypeConverterFormat {
            get {
                return ResourceManager.GetString("NoTypeConverterFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The argument &apos;{0}&apos; cannot be null..
        /// </summary>
        internal static string NullArgumentValueFormat {
            get {
                return ResourceManager.GetString("NullArgumentValueFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property defining the argument &apos;{0}&apos; doesn&apos;t have a public set accessor..
        /// </summary>
        internal static string PropertyIsReadOnlyFormat {
            get {
                return ResourceManager.GetString("PropertyIsReadOnlyFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RequiresAnyAttribute requires at least two arguments; use CommandLineArgumentAttribute.IsRequired to make a single argument required..
        /// </summary>
        internal static string RequiresAnySingleArgument {
            get {
                return ResourceManager.GetString("RequiresAnySingleArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred setting the value of argument &apos;{0}&apos;: {1}.
        /// </summary>
        internal static string SetValueErrorFormat {
            get {
                return ResourceManager.GetString("SetValueErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many arguments were supplied..
        /// </summary>
        internal static string TooManyArguments {
            get {
                return ResourceManager.GetString("TooManyArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not convert type &apos;{0}&apos; to &apos;{1}&apos; for argument &apos;{2}&apos;..
        /// </summary>
        internal static string TypeConversionErrorFormat {
            get {
                return ResourceManager.GetString("TypeConversionErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{0}&apos; does not derive from the ShellCommand class or does not define the ShellCommandAttribute attribute..
        /// </summary>
        internal static string TypeIsNotShellCommandFormat {
            get {
                return ResourceManager.GetString("TypeIsNotShellCommandFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type must be a generic type definition..
        /// </summary>
        internal static string TypeNotGenericDefinition {
            get {
                return ResourceManager.GetString("TypeNotGenericDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown argument name &apos;{0}&apos;..
        /// </summary>
        internal static string UnknownArgumentFormat {
            get {
                return ResourceManager.GetString("UnknownArgumentFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A {0} refers to an unknown argument &apos;{1}&apos;..
        /// </summary>
        internal static string UnknownDependencyFormat {
            get {
                return ResourceManager.GetString("UnknownDependencyFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown version..
        /// </summary>
        internal static string UnknownVersion {
            get {
                return ResourceManager.GetString("UnknownVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unspecified error has occurred..
        /// </summary>
        internal static string UnspecifiedError {
            get {
                return ResourceManager.GetString("UnspecifiedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The argument &apos;{0}&apos; must have between {1} and {2} items..
        /// </summary>
        internal static string ValidateCountBothFormat {
            get {
                return ResourceManager.GetString("ValidateCountBothFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The argument &apos;{0}&apos; must have at most {1} items..
        /// </summary>
        internal static string ValidateCountMaxFormat {
            get {
                return ResourceManager.GetString("ValidateCountMaxFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The argument &apos;{0}&apos; must have at least {1} items..
        /// </summary>
        internal static string ValidateCountMinFormat {
            get {
                return ResourceManager.GetString("ValidateCountMinFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must have between {0} and {1} items..
        /// </summary>
        internal static string ValidateCountUsageHelpBothFormat {
            get {
                return ResourceManager.GetString("ValidateCountUsageHelpBothFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must have at most {0} items..
        /// </summary>
        internal static string ValidateCountUsageHelpMaxFormat {
            get {
                return ResourceManager.GetString("ValidateCountUsageHelpMaxFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must have at least {0} items..
        /// </summary>
        internal static string ValidateCountUsageHelpMinFormat {
            get {
                return ResourceManager.GetString("ValidateCountUsageHelpMinFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The argument &apos;{0}&apos; must not be empty..
        /// </summary>
        internal static string ValidateNotEmptyFailedFormat {
            get {
                return ResourceManager.GetString("ValidateNotEmptyFailedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must not be empty..
        /// </summary>
        internal static string ValidateNotEmptyUsageHelp {
            get {
                return ResourceManager.GetString("ValidateNotEmptyUsageHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The argument &apos;{0}&apos; must not be empty or contain only white-space characters..
        /// </summary>
        internal static string ValidateNotWhiteSpaceFailedFormat {
            get {
                return ResourceManager.GetString("ValidateNotWhiteSpaceFailedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must not be empty or white-space..
        /// </summary>
        internal static string ValidateNotWhiteSpaceUsageHelp {
            get {
                return ResourceManager.GetString("ValidateNotWhiteSpaceUsageHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The argument &apos;{0}&apos; cannot be used together with: {1}..
        /// </summary>
        internal static string ValidateProhibitsFailedFormat {
            get {
                return ResourceManager.GetString("ValidateProhibitsFailedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot be used with: {0}..
        /// </summary>
        internal static string ValidateProhibitsUsageHelpFormat {
            get {
                return ResourceManager.GetString("ValidateProhibitsUsageHelpFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The argument &apos;{0}&apos; must be between {1} and {2}..
        /// </summary>
        internal static string ValidateRangeFailedBothFormat {
            get {
                return ResourceManager.GetString("ValidateRangeFailedBothFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The argument &apos;{0}&apos; must be most {1}..
        /// </summary>
        internal static string ValidateRangeFailedMaxFormat {
            get {
                return ResourceManager.GetString("ValidateRangeFailedMaxFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The argument &apos;{0}&apos; must be at least {1}..
        /// </summary>
        internal static string ValidateRangeFailedMinFormat {
            get {
                return ResourceManager.GetString("ValidateRangeFailedMinFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be between {0} and {1}..
        /// </summary>
        internal static string ValidateRangeUsageHelpBothFormat {
            get {
                return ResourceManager.GetString("ValidateRangeUsageHelpBothFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be at most {0}..
        /// </summary>
        internal static string ValidateRangeUsageHelpMaxFormat {
            get {
                return ResourceManager.GetString("ValidateRangeUsageHelpMaxFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be at least {0}..
        /// </summary>
        internal static string ValidateRangeUsageHelpMinFormat {
            get {
                return ResourceManager.GetString("ValidateRangeUsageHelpMinFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must use at least one of: {0}..
        /// </summary>
        internal static string ValidateRequiresAnyFailedFormat {
            get {
                return ResourceManager.GetString("ValidateRequiresAnyFailedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The argument &apos;{0}&apos; must be used together with: {1}..
        /// </summary>
        internal static string ValidateRequiresFailedFormat {
            get {
                return ResourceManager.GetString("ValidateRequiresFailedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be used with: {0}..
        /// </summary>
        internal static string ValidateRequiresUsageHelpFormat {
            get {
                return ResourceManager.GetString("ValidateRequiresUsageHelpFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The argument &apos;{0}&apos; must be between {1} and {2} characters..
        /// </summary>
        internal static string ValidateStringLengthBothFormat {
            get {
                return ResourceManager.GetString("ValidateStringLengthBothFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The argument &apos;{0}&apos; must be at most {1} characters..
        /// </summary>
        internal static string ValidateStringLengthMaxFormat {
            get {
                return ResourceManager.GetString("ValidateStringLengthMaxFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The argument &apos;{0}&apos; must be at least {1} characters..
        /// </summary>
        internal static string ValidateStringLengthMinFormat {
            get {
                return ResourceManager.GetString("ValidateStringLengthMinFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be between {0} and {1} characters..
        /// </summary>
        internal static string ValidateStringLengthUsageHelpBothFormat {
            get {
                return ResourceManager.GetString("ValidateStringLengthUsageHelpBothFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be at most {0} characters..
        /// </summary>
        internal static string ValidateStringLengthUsageHelpMaxFormat {
            get {
                return ResourceManager.GetString("ValidateStringLengthUsageHelpMaxFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be at least {0} characters..
        /// </summary>
        internal static string ValidateStringLengthUsageHelpMinFormat {
            get {
                return ResourceManager.GetString("ValidateStringLengthUsageHelpMinFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value for the argument &apos;{0}&apos; is not valid..
        /// </summary>
        internal static string ValidationFailedFormat {
            get {
                return ResourceManager.GetString("ValidationFailedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value must be zero or larger..
        /// </summary>
        internal static string ValueMustBeNonNegative {
            get {
                return ResourceManager.GetString("ValueMustBeNonNegative", resourceCulture);
            }
        }
    }
}
