using Microsoft.CodeAnalysis;
using System.Text;

namespace Ookii.CommandLine.Generator;

internal class SourceBuilder
{
    private readonly StringBuilder _builder = new();
    private int _indentLevel;
    private bool _startOfLine = true;

    public SourceBuilder(INamespaceSymbol ns)
        : this(ns.IsGlobalNamespace ? null : ns.ToDisplayString())
    {
    }

    public SourceBuilder(string? ns)
    {
        _builder.AppendLine("// <auto-generated>");
        _builder.AppendLine("#nullable enable");
        _builder.AppendLine();
        if (ns != null)
        {
            AppendLine($"namespace {ns}");
            OpenBlock();
        }
    }

    public void Append(string text)
    {
        WriteIndent();
        _builder.Append(text);
        _startOfLine = false;
    }

    public void AppendLine()
    {
        _builder.AppendLine();
        _startOfLine = true;
    }

    public void AppendLine(string text)
    {
        WriteIndent();
        _builder.AppendLine(text);
        _startOfLine = true;
    }

    public void OpenBlock()
    {
        AppendLine("{");
        ++_indentLevel;
    }

    public void CloseBlock()
    {
        --_indentLevel;
        AppendLine("}");
    }

    public string GetSource()
    {
        while (_indentLevel > 0)
        {
            CloseBlock();
        }

        return _builder.ToString();
    }

    public void IncreaseIndent() => ++_indentLevel;

    public void DecreaseIndent() => --_indentLevel;

    private void WriteIndent()
    {
        if (_startOfLine)
        {
            _builder.Append(' ', _indentLevel * 4);
        }
    }
}
