// Copyright (c) Sven Groot (Ookii.org)
using System;
using System.Collections.Generic;
using System.Text;

namespace Ookii.CommandLine
{
    /// <summary>
    /// Defines an alternative short name for a command line argument.
    /// </summary>
    /// <remarks>
    /// <note>
    ///   To specify multiple aliases, apply this attribute multiple times.
    /// </note>
    /// <note>
    ///   This attribute specifies short name aliases used with <see cref="ParsingMode.LongShort"/>.
    ///   It is ignored if <see cref="CommandLineParser.Mode"/> is not <see cref="ParsingMode.LongShort"/>,
    ///   or if the argument doesn't also have a primary <see cref="CommandLineArgumentAttribute.ShortName"/>.
    /// </note>
    /// <para>
    ///   The short aliases for a command line argument can be used instead of the regular short
    ///   name to specify the parameter on the command line.
    /// </para>
    /// <para>
    ///   All short argument names and short aliases defined by a single arguments type must be
    ///   unique.
    /// </para>
    /// <para>
    ///   By default, the command line usage help generated by <see cref="CommandLineParser.WriteUsage(System.IO.TextWriter,int,WriteUsageOptions)"/>
    ///   does not list the aliases. Either manually add them to the description, or set the <see cref="WriteUsageOptions.IncludeAliasInDescription"/>
    ///   property to <see langword="true"/>.
    /// </para>
    /// </remarks>
    [AttributeUsage(AttributeTargets.Property | AttributeTargets.Parameter, AllowMultiple=true)]
    public sealed class ShortAliasAttribute : Attribute
    {
        private readonly char _alias;

        /// <summary>
        /// Initializes a new instance of the <see cref="AliasAttribute"/> class.
        /// </summary>
        /// <param name="alias">The alternative short name for the command line argument.</param>
        public ShortAliasAttribute(char alias)
        {
            _alias = alias;
        }

        /// <summary>
        /// Gets the alternative short name for the command line argument.
        /// </summary>
        /// <value>
        /// The alternative short name for the command line argument.
        /// </value>
        public char Alias => _alias;
    }
}
